<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Создать пост</title>
</head>
<body>
<header>
    <h1>Мой блог - новый пост</h1>
</header>
<nav>
    <ul>
        <li>
            <a href="/posts">Посты</a>
        </li>
    </ul>
</nav>
<a href="/posts">Блог</a>

<form action="/posts" method="post">
    <?php require '_form.phtml' ?>
    <input type="submit" value="Создать">
</form>
</body>
</html>
