<a href="/users">Все Пользователи</a>

<!-- BEGIN (write your solution here) -->
<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>
<hr>

<ul>
    <?php foreach ($users as $user) : ?>
        <li>
            <i><?= $user['firstName'] ?></i>
        </li>
    <?php endforeach ?>
</ul>
<!-- END -->
