<h1>Edit User</h1>
<?php if (!empty($flash)) : ?>
    <?php foreach ($flash as $type => $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <div style="color: green;" class="flash flash-<?= htmlspecialchars($type) ?>">
                <?= htmlspecialchars($message) ?>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>
<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <input type="hidden" name="user[id]" value="<?= htmlspecialchars($user['id']) ?>" required/>
        <label>
            Nickname:
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>" required/>
        </label>
        <?php if (isset($errors['nickname'])): ?>
            <div><?= $errors['nickname'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email:
            <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>" required/>
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Submit" />
</form>
<a href=<?= $router->urlFor('users') ?>>Back to users</a>