<h1>Users</h1>
<form action=<?= $router->urlFor('users') ?> method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>
<?php if (!empty($flash)) : ?>
    <?php foreach ($flash as $type => $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <div style="color: green;" class="flash flash-<?= htmlspecialchars($type) ?>">
                <?= htmlspecialchars($message) ?>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>
<hr>
<table>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <?= $user['nickname'] ?>
            </td>
            <td>
                <?= $user['email'] ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<a href=<?= $router->urlFor('users.new') ?>>New User</a>