<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>
<hr>
<table>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <?= $user['nickname'] ?>
            </td>
            <td>
                <?= $user['email'] ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<a href="/users/new">New User</a>