<h1>New User</h1>
<hr>
<form action=<?= $router->urlFor('users.store') ?> method="post">
    <div>
        <label>
            Nickname:
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>" required/>
        </label>
    </div>
    <div>
        <label>
            Email:
            <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>" required/>
        </label>
    </div>
    <input type="submit" value="Submit" />
</form>